### ISSUE TITLE
How to pass data between @on() functions

### ISSUE THREAD

**Issue by AlexWennerDT** [h2oai/wave#831] opened 2021-05-21 19:25 UTC
Ideally I would like to return an expression in one @on() async and then pass it into another @on() async as a parameter, but the logic is difficult for me to wrap my head around. Would there be any examples of this I could refer to by chance? Or let alone any possibility of this?

**Comment by AlexWennerDT** [comment] 2021-05-21 19:55
Current workaround: declaring and setting global variable in one async function and using it in another. Feels like I am decreasing readability of the code and just in general enabling bad practice.

**Comment by mtanco** [comment] 2021-05-21 20:33
Hi @AlexWennerDT, do you have an example use case you could share with us on how this would work or what the goal is? Are the two on function calls to the `on` functions happening from two separate calls to the Serve function?

In general, we see the solution to save information that needs to be used in different parts of the app into `q.client`, `q.user`, or `q.app` variables depending on who needs to have access to the variable.

**Comment by lo5** [comment] 2021-05-24 18:08
Simpler pattern: instead of calling one `@on` function from another, simply define another function with formal parameters and call it from both your `@on` functions.

```py
async def do_something(q, x, y):
    ...
   await q.page.save()


@on('#foo')
async def show_foo(q):
    ...
    await do_something(q, x, y)


@on('#bar')
async def show_bar(q):
    ...
    await do_something(q, x, y)
```

**Comment by AlexWennerDT** [comment] 2021-05-25 14:40
Hi I apologize I thought I had reached back out with an example. The variable 'selected_close' is what ideally would be passed between on functions. @lo5 I think this could work, thank you for the example! I also see how @mtanco's storing this variable in q.user or q.client would work as well. This variable would be user exclusive.
![image](https://user-images.githubusercontent.com/78372056/119517448-3c76b780-bd3d-11eb-9064-b6cee687fb4f.png)

**Comment by AlexWennerDT** [comment] 2021-05-25 14:43
Side note, the delete_dialog(q) is a function that I set q.page['meta'].dialog = None, because without doing that after the dialog persists. I have seen this addressed in an issue, is this still necessary in 0.15?

**Comment by lo5** [comment] 2021-05-25 17:56
@AlexWennerDT `q.page['meta'].dialog = None` is required. This is not a bug. The dialog needs to be closed by the app because it gives the app a chance to validate any inputs made on the dialog, and keep the dialog open until those inputs are fixed by the user.

**Comment by AlexWennerDT** [comment] 2021-05-26 14:09
Thanks for the recommendations of solving this! It helped a lot!

**Closed** 2021-05-26 14:09 UTC
Labels: question
