### ISSUE TITLE
httpx.ReadTimeout 

### ISSUE THREAD

**Issue by Boadzie** [h2oai/wave#1759] opened 2022-12-13 06:57 UTC
httpx.ReadTimeout h2o wave

**Comment by mturoci** [comment] 2022-12-13 07:29
Can you add more details? Like when this happens, what's your configuration etc  Thanks!

**Comment by Boadzie** [comment] 2022-12-13 07:32
I set  H2O_WAVE_MAX_REQUEST_SIZE=100m and added a new chart. It showed the UI for a while and then the screen went blank

**Comment by mturoci** [comment] 2022-12-13 07:47
Can you put up a small example app that I could run and debug myself? This is still quite vague.

**Comment by Boadzie** [comment] 2022-12-14 07:30
This is the code 

from h2o_wave import Q, ui, main, app
import pandas as pd
from siuba import *
from siuba.siu import call
from charts import show_table, streaming_service, fav_age_effect, fav_depression, fav_insomnia


# read the data anc cover
music = pd.read_csv("../music_mental_survey_clean.csv")
music = music >> select(~_["Unnamed: 0"])  # remove unwanted column


@app("/")
async def serve(q: Q):
    q.page["meta"] = ui.meta_card(
        box="",
        themes=[
            ui.theme(
                name="cool7",
                primary="#ffffff",
                text="#ffffff",
                card="#111111",
                page="#ffffff",
            )
        ],
        theme="cool7",
    )
    q.page["header"] = ui.header_card(
        box=("1 1 10 1"),
        icon="HealthRefresh",
        color="card",
        title="Music's effect on Mental Health",
        subtitle="Can music impact mental health? Let's find out",
    )
    q.page["table"] = ui.form_card(
        box=("1 2 3 5"),
        title="Music and Mental Condition Dataset",
        items=[await show_table(df=music)],
    )

    q.page["streaming_service"] = ui.frame_card(
        box=("4 2 3 5"),
        title="Most popular streaming service",
        content=await streaming_service(df=music),
    )

    q.page["fav_depression"] = ui.frame_card(
        box=("7 2 4 5"),
        title="",
        content=await fav_depression(df=music),
    )

    q.page["fav_age_effect"] = ui.frame_card(
        box=("1 7 5 5"),
        title="",
        content=await fav_age_effect(df=music),
    )

    q.page["fav_insomnia"] = ui.frame_card(
        box=("6 7 5 5"),
        title="",
        content=await fav_insomnia(df=music),
    )

    await q.page.save()

**Comment by mturoci** [comment] 2022-12-14 10:19
Thanks @Boadzie, this is helpful.

>I set H2O_WAVE_MAX_REQUEST_SIZE=100m

I think there is a typo, should be `100M` instead of `100m`. Could you please try that one? (This assumes the data is <= 100Mb).

re stacktrace: I was working on this yesterday and figured this is a bug in the underlying HTTP lib we use under the hood. Once [this PR ](https://github.com/encode/httpcore/pull/641) is merged, I will be able to properly handle the response and display the warning about misconfiguration.

**Comment by Boadzie** [comment] 2022-12-14 13:41
Ok thanks for the reply

**Comment by Boadzie** [comment] 2022-12-14 13:42
Unfortunately the error persist.

**Comment by mturoci** [comment] 2022-12-14 15:03
Can you please add `music_mental_survey_clean.csv` here so that I could try it out?

**Comment by Boadzie** [comment] 2022-12-14 15:32
sure
[music_mental_survey_clean.csv](https://github.com/h2oai/wave/files/10229178/music_mental_survey_clean.csv)

**Comment by mturoci** [comment] 2022-12-15 07:47
Okay, so the CSV is very small ~ 150kb, which is not a problem.

I tried this and works:

```py
from h2o_wave import Q, ui, main, app
import pandas as pd


# read the data anc cover
music = pd.read_csv("music_mental_survey_clean.csv")


@app("/")
async def serve(q: Q):
    q.page["header"] = ui.header_card(
        box=("1 1 10 1"),
        icon="HealthRefresh",
        color="card",
        title="Music's effect on Mental Health",
        subtitle="Can music impact mental health? Let's find out",
    )

    q.page['data'] = ui.markup_card(box='2 2 4 4', title='aa', content=music.to_html())

    await q.page.save()

```

Can you show me the code for `from charts import show_table, streaming_service, fav_age_effect, fav_depression, fav_insomnia` these functions? I guess you are using some kind of 3rd party lib that is embedding its own JS which is super big.

**Comment by Boadzie** [comment] 2022-12-15 10:07
Yea sure

```python
from h2o_wave import Q, ui
from siuba import *
from siuba.siu import call
import plotly.express as px
import plotly.io as pio
from plotly import graph_objects as go

pio.templates.default = "plotly_dark"


def update_chart(fig):

    return fig.update(
        layout=go.Layout(margin=dict(t=40, r=0, b=40, l=0), legend=dict(yanchor="top", y=0.95, xanchor="left", x=0.01))
    )


# show table of data
async def show_table(df):
    return ui.table(
        name="table",
        height="410px",
        # Add pagination attribute to make your table paginated.
        pagination=ui.table_pagination(total_rows=100, rows_per_page=5),
        events=["page_change"],
        columns=[ui.table_column(name=x, label=x) for x in df.columns.tolist()],
        rows=[ui.table_row(name=str(i), cells=list(map(str, df.values.tolist()[i]))) for i in df.index[0:100]],
    )


async def age_hist(df):
    fig = df >> call(px.histogram, x="age", data_frame=_, labels={"age": "Age"})
    update_chart(fig)
    html = pio.to_html(fig, config=None, auto_play=True, include_plotlyjs=True)
    return html


async def streaming_service(df):
    fig = df >> call(
        px.histogram,
        x="primary_streaming_service",
        data_frame=_,
        labels={"primary_streaming_service": "Primary Streaming Service"},
    )
    fig.update_xaxes(categoryorder="total descending")
    update_chart(fig)
    html = pio.to_html(fig, config=None, auto_play=True, include_plotlyjs=True)
    return html


async def fav_age_effect(df):
    fig = df >> call(
        px.histogram,
        x="fav_genre",
        y="age",
        color="music_effects",
        data_frame=_,
        text_auto=True,
        histfunc="avg",
        barmode="group",
        title="Music Effect on Listeners - Age",
        labels={"fav_genre": "Fav Genre", "age": "Age"},
    )

    update_chart(fig)
    html = pio.to_html(fig, config=None, auto_play=True, include_plotlyjs=True)
    return html


async def fav_depression(df):
    fig = df >> call(
        px.histogram,
        x="fav_genre",
        y="depression",
        color="music_effects",
        data_frame=_,
        text_auto=True,
        histfunc="avg",
        barmode="group",
        title="Music Effect on Listeners - Depression",
        labels={"fav_genre": "Fav Genre", "depression": "Depression"},
    )

    fig.update_yaxes(title="Depression", range=[0, 10])
    update_chart(fig)
    html = pio.to_html(fig, config=None, auto_play=True, include_plotlyjs=True)
    return html


async def fav_insomnia(df):
    fig = df >> call(
        px.histogram,
        y="insomnia",
        x="fav_genre",
        color="music_effects",
        data_frame=_,
        text_auto=True,
        histfunc="avg",
        barmode="group",
        title="Music Effect on Listeners - Insomnia",
        labels={"fav_genre": "Fav Genre", "insomnia": "Insomnia"},
    )

    fig.update_yaxes(title="Insomnia", range=[0, 10])
    update_chart(fig)
    html = pio.to_html(fig, config=None, auto_play=True, include_plotlyjs=True)
    return html
```

**Comment by mturoci** [comment] 2022-12-15 10:50
Ah okay, the problem is you are pushing the same plotlyjs 5 times (`include_plotlyjs=True`). Try replacing it with `include_plotlyjs='cdn'` instead so that the JS won't be embedded within the HTML you are sending.

**Comment by mturoci** [comment] 2022-12-16 08:35
Glad it worked! Would you mind sharing your app in https://github.com/h2oai/wave/discussions/1632 once finished?

**Closed by mturoci** 2022-12-16 08:35 UTC
Labels: question

**Comment by Boadzie** [comment] 2022-12-16 10:20
sure
