### ISSUE TITLE
Table pagination arrows does not show up!

### ISSUE THREAD

**Issue by uunal** [h2oai/wave#1745] opened 2022-12-09 11:10 UTC
#### Wave SDK Version, OS
wave : 0.24.1 / Windows

#### Actual behavior
Tried example below:
https://wave.h2o.ai/docs/examples/table-pagination-download

Pagination arrows does not show up.

#### Expected behavior

It should show arrows so event could be triggerd.

#### Steps To Reproduce

1. run example code.

**Comment by mturoci** [comment] 2022-12-09 11:19
Hi @uunal. Seems to render fine for me

<img width="1659" alt="image" src="https://user-images.githubusercontent.com/64769322/206691037-b0aed379-5a76-493e-90a3-2d0b2174bce6.png">

What browser (+ version) did you use? Also can you provide a screenshot of what you see and the command you used to run the example? Thanks!

**Comment by mturoci** [comment] 2022-12-12 07:50
Closing for now since neither I nor @marek-mihok could repro this. @uunal feel free to reopen if you manage to provide reproducible steps.

**Closed by mturoci** 2022-12-12 07:50 UTC
Labels: bug

**Comment by uunal** [comment] 2022-12-12 07:56
Thank you for the fast response, it was because of running environment had different version of wave. 
I've managed to replicate the example as standalone without error too.

**Comment by mturoci** [comment] 2022-12-12 08:05
Thanks @uunal.
