### ISSUE TITLE
Dropdown options appear off to the left side of input element

### ISSUE THREAD

**Issue by brmscheiner** [h2oai/wave#592] opened 2021-03-01 21:56 UTC
#### Wave SDK Version, OS

Chrome 88.0.4324.192
Wave 0.12.1
Max OSX

#### Actual behavior

Dropdown options appear off to the left side of input element

![image](https://user-images.githubusercontent.com/9775178/109563964-4d44c380-7a95-11eb-8e36-5dcd5bdc6eed.png)

#### Expected behavior

Dropdown options appear below the input element 
![image](https://user-images.githubusercontent.com/9775178/109564239-a3196b80-7a95-11eb-8553-4ca79f162772.png)

#### Steps To Reproduce

Create a dropdown with 20+ choices

**Comment by mturoci** [comment] 2021-03-02 12:33
Hi @brmscheiner this is desired behavior of the component Framework we use. Displaying the options to the left instead of under the dropdown provides more space. The point is to show as many items as possible.

Duplicate of https://github.com/h2oai/wave/issues/149.

**Closed by mturoci** 2021-03-02 12:33 UTC
Labels: bug

**Comment by brmscheiner** [comment] 2021-03-02 18:21
Hmmm, I feel like the better pattern is to make the list scrollable when there are lots of items. Fluent doesn't support this?

**Comment by mturoci** [comment] 2021-03-03 07:32
It is scrollable if the number of items exceeds available viewport, it just tries to use as much space as possible. It is possible to force to always render at the bottom, but we have agreed with @lo5 that it is not worth it.
