### ISSUE TITLE
Date Picker widget shows the date previous to what was selected

### ISSUE THREAD

**Issue by debugaftercoffee** [h2oai/wave#1184] opened 2022-01-11 18:47 UTC
#### Wave SDK Version, OS

Wave SDK and runtime: 0.19.0, OS: Mac OS and Linux

#### Actual behavior

When selecting a date from a date picker, the previous day is presented on the UI, but the value in the q.args is correct. You can reproduce this behavior using the [Date Picker Sample](https://wave.h2o.ai/docs/examples/date-picker). In the screenshot below I have selected *October 24th 2017* in each widget and the presented value is *October 23rd 2017*.
![selection](https://user-images.githubusercontent.com/65924811/149002116-2ee2ee5b-3221-420e-b99f-d7cd06ec7986.png)

After enter submit the correct dates are displayed.
![results](https://user-images.githubusercontent.com/65924811/149002141-f6cb6dfa-f843-4d75-a446-4c5f318007b8.png)

#### Expected behavior
The date the user selects should be displayed in the date picker widget.

#### Steps To Reproduce
1. Run the [Date Picker Sample](https://wave.h2o.ai/docs/examples/date-picker). 
2. Select October 24th 2017 and verify the 3 editable widgets show October 23rd 2017.
3. Click *Submit* and verify October 24th 2017 is displayed for the 3 editable widgets.

**Comment by mtanco** [comment] 2022-01-12 04:11
Hi @debugaftercoffee, thanks for the great details! 

This was tracked in #1098 and has been fixed, the fix will be available in the next release. As a note, this is a timezone issue so you'll probably find you don't always see the issue, and many of our uses in the Europe timezones probably never noticed.

**Comment by mturoci** [comment] 2022-01-12 12:15
Thanks @debugaftercoffee, closing as duplicate of #1098.

**Closed by mturoci** 2022-01-12 12:15 UTC
Labels: bug

**Comment by debugaftercoffee** [comment] 2022-01-12 17:12
@mtanco @mturoci thank you for the link to the fix!
