### ISSUE TITLE
Wave scripts running fine BUT Wave Apps not working. No error in screen. Web server started but I see only Wave Live logo only in browser.

### ISSUE THREAD

**Issue by THESHAMIK** [h2oai/wave#1436] opened 2022-05-20 05:16 UTC
Hi, Installed H20 Wave recently - 0.21.1.
Everything is working for me for Wave scripts.
But when I am running wave apps, it not working.
Web server started-no issues.
But in the browser http://localhost:10101/tour I see only Wave Live logo only.

Similar to A Tour and Demo of Wave doesn't work (VPN/Proxy related) #725 OR #1091.
In mine case also tour.py is not working.

I am using Windows 11, python 3.7 & Anaconda.
Even a basic prog is not working like:
from h2o_wave import Q, ui, app, main
from h2o_wave import site

@app('/')
async def serve(q: Q):
await q.page.drop()
site = q.site
q.page['random'] = ui.form_card(box='1 12 5 2', items=[ui.progress('Running...')])
await q.page.save()

There is no error at all. This is what I get after starting the webserver 👍

(aqua_h2o) C:\Users\shamik.bhattacharya\wave>wave run app.py
params: []2022/05/19 19:29:14 #
2022/05/19 19:29:14 # ┌────────────────┐ H2O Wave
2022/05/19 19:29:14 # │ ┐┌┐┐┌─┐┌ ┌┌─┐ │ 0.21.1 20220512131635
2022/05/19 19:29:14 # │ └┘└┘└─└└─┘└── │ © 2021 H2O.ai, Inc.
2022/05/19 19:29:14 # └────────────────┘
2022/05/19 19:29:14 #
2022/05/19 19:29:14 # {"address":":10101","base-url":"/","t":"listen","web-dir":"D:\Anaconda3\envs\aqua_h2o\www"}
�[32mINFO�[0m: Will watch for changes in these directories: ['C:\Users\shamik.bhattacharya\wave']
�[32mINFO�[0m: Uvicorn running on �[1mhttp://127.0.0.1:8000�[0m (Press CTRL+C to quit)
�[32mINFO�[0m: Started reloader process [�[36m�[1m22444�[0m] using �[36m�[1mstatreload�[0m
�[32mINFO�[0m: Started server process [�[36m20092�[0m]
�[32mINFO�[0m: Waiting for application startup.
�[32mINFO�[0m: Application startup complete.

But why in browser its only wave logo?
Similarly when I run tour.py all seems well ::::

(aqua_h2o) C:\Users\shamik.bhattacharya\wave\examples>wave run tour
params: []2022/05/20 10:40:53 #
2022/05/20 10:40:53 # ┌────────────────┐ H2O Wave
2022/05/20 10:40:53 # │  ┐┌┐┐┌─┐┌ ┌┌─┐ │ 0.21.1 20220512131635
2022/05/20 10:40:53 # │  └┘└┘└─└└─┘└── │ © 2021 H2O.ai, Inc.
2022/05/20 10:40:53 # └────────────────┘
2022/05/20 10:40:53 #
2022/05/20 10:40:53 # {"address":":10101","base-url":"/","t":"listen","web-dir":"D:\\Anaconda3\\envs\\aqua_h2o\\www"}
[32mINFO[0m:     Will watch for changes in these directories: ['C:\\Users\\shamik.bhattacharya\\wave\\examples']
[32mINFO[0m:     Uvicorn running on [1mhttp://127.0.0.1:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     Started reloader process [[36m[1m22688[0m] using [36m[1mstatreload[0m
----------------------------------------
 Welcome to the H2O Wave Interactive Tour!

 Go to http://localhost:10101/tour
----------------------------------------
[32mINFO[0m:     Started server process [[36m20936[0m]
[32mINFO[0m:     Waiting for application startup.
2022/05/20 10:40:57 # {"host":"http://127.0.0.1:8000","route":"/tour","t":"app_add"}
[32mINFO[0m:     Application startup complete.
2022/05/20 10:41:00 # {"addr":"[::1]:56349","route":"/","t":"ui_add"}

But 
[error_wave.docx](https://github.com/h2oai/wave/files/8736112/error_wave.docx)
in browser its only wave logo?

Pl help.

**Comment by THESHAMIK** [comment] 2022-05-20 05:20
It seems web server is UP & running but App server is NOT up. Maybe that is why wave scripts are running fine but not wave apps.
If that is the case how to debug for web app...Kindly guide..

**Comment by THESHAMIK** [comment] 2022-05-20 05:40
Also for wave scripts when using Jupyter
[403 wave error.docx](https://github.com/h2oai/wave/files/8736212/403.wave.error.docx)
, I am getting 403 error.

---------------------------------------------------------------------------
ServiceError                              Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_24092\615144231.py in <module>
     15 
     16 # Finally, sync the page to send our changes to the server.
---> 17 page.save()

D:\Anaconda3\envs\aqua_h2o\lib\site-packages\h2o_wave\core.py in save(self)
    565         if p:
    566             logger.debug(data)
--> 567             self.site._save(self.url, p)
    568 
    569 

D:\Anaconda3\envs\aqua_h2o\lib\site-packages\h2o_wave\core.py in _save(self, url, patch)
    630         res = self._http.patch(_rebase(_config.hub_address, url), content=patch)
    631         if res.status_code != 200:
--> 632             raise ServiceError(f'Request failed (code={res.status_code}): {res.text}')
    633 
    634     def load(self, url) -> dict:

ServiceError: Request failed (code=403):

403 Forbidden: incorrect proxy service was requested

**Comment by mturoci** [comment] 2022-05-20 06:58
Closing as duplicate of #1422.

**Closed by mturoci** 2022-05-20 06:58 UTC
Labels: bug

**Comment by THESHAMIK** [comment] 2022-05-20 08:52
Hello yes this last point was duplicate but core issue was different. For future reference if someone stumbles on this type of error that is wave script working but wave Apps not working. It was solved by basically taking proxy out. Once you bypass proxy it starts working. Thanks.
