### ISSUE TITLE
New Component: Collapsable Table

### ISSUE THREAD

**Issue by iamabhishekmathur** [h2oai/wave#975] opened 2021-08-19 17:36 UTC
## Collapsable Table

![image](https://user-images.githubusercontent.com/42759212/130116765-fa3df78b-606c-46a1-a263-0e5b8d1d9e09.png)

## Features
- Same features as the regular table #974 
- Rows should be collapsable/expandable
- Expanded columns can have a header different from the columns of the main rows (optional)

**Comment by iamabhishekmathur** [comment] 2021-08-19 17:38
cc: @sandruparo @dulajra @mwysokin

**Comment by mturoci** [comment] 2021-08-20 07:37
Duplicate of #961.

**Closed by mturoci** 2021-08-20 07:37 UTC
Labels: feature

**Comment by mtanco** [comment] 2021-08-24 23:04
I believe this is actually a re-design of the ui.table group able feature, where the grouped column is hard-coded
