### ISSUE TITLE
Form card with height of 1 overflows if a single ui.stat is used

### ISSUE THREAD

**Issue by dott1718** [h2oai/wave#723] opened 2021-04-07 11:48 UTC
#### Wave SDK Version, OS

Wave 0.13.0, Firefox

#### Actual behavior
```py
q.page["card_example"] = ui.form_card(
  box="4 2 6 1",
  items=[
      ui.stats(
          [
              ui.stat(
                  value="ZZZ",
                  label="",
                  icon="PlugConnected",
                  caption="ZZZ",
              )
          ]
      )
  ],
)
```
Creates a card with a single ui.stat component and has the height of 1, but it overflows in the browser (see the screenshot)

#### Expected behavior

It makes sense to adjust the paddings to not overflow in such case.

![image](https://user-images.githubusercontent.com/12784356/113861355-6a149b00-97a7-11eb-93c3-125eb0c0abba.png)

**Comment by lo5** [comment] 2021-04-07 23:55
@dott1718 - the `ui.stat()` wasn't designed for a 1-unit high form. I would recommend building apps with the responsive layout system (`ui.layout()`) so that the heights auto-adjust.

**Comment by mturoci** [comment] 2021-08-11 09:53
Closing as expected behavior since `ui.stat` wasn't designed for such small forms.

**Closed by mturoci** 2021-08-11 09:53 UTC
Labels: ui, bug
