### ISSUE TITLE
Cannot download a file

### ISSUE THREAD

**Issue by Daniel-Kelvich** [h2oai/wave#1491] opened 2022-06-09 08:03 UTC
#### Wave SDK Version, OS

0.22.0, Ubuntu 21.04, Firefox brower

#### Actual behavior

Cannot download a file from the server. The I click the link a file just opens in a new tab.

#### Expected behavior

To automatically download a file when a user clicks on the link.

#### Steps To Reproduce
```
from h2o_wave import main, app, Q, ui

@app('/downloads')
async def serve(q: Q):
    download_path, = await q.site.upload(['data/img.png'])
    q.page['download'] = ui.form_card(box='1 1 2 2', items = [
        ui.link(label='Download Results', path=download_path, download=True, button=True),
    ])

    await q.page.save()
```

**Comment by mturoci** [comment] 2022-06-13 09:46
Duplicate of #999

**Closed by mturoci** 2022-06-13 09:46 UTC
Labels: question
