### ISSUE TITLE
Warn if driver is incompatible with server

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave#298] opened 2020-11-12 17:26 UTC
Several internal folks have ran into issues because their python client and waved server versions have not matched. We should include checking and error handling for this. Probably the app should completely fail (as they tend to silently fail like completely white pages) or at least log errors to the console.

**Comment by lo5** [comment] 2021-03-26 02:58
Duplicate of #265

**Closed by lo5** 2021-03-26 02:58 UTC
Labels: feature, py, server
