### ISSUE TITLE
wave fetch command returning a 404 on MacOS arm64

### ISSUE THREAD

**Issue by nipunchamikara** [h2oai/wave#2186] opened 2023-11-07 13:26 UTC
#### Wave SDK Version, OS

1.0.0, macOS 14.1 arm64

#### Actual behavior

On running `wave fetch` in the terminal, a 404 error occurs. There seems to be an issue with the platform name set to `macosx_12_0_arm64` instead of `darwin` since [wave-1.0.0-darwin-arm64.tar.gz](https://github.com/h2oai/wave/releases/download/v1.0.0/wave-1.0.0-darwin-arm64.tar.gz) exists. Might be an OS-specific issue. The output is as follows:

```bash
Fetching examples and related files. Please wait...
Downloading https://github.com/h2oai/wave/releases/download/v1.0.0/wave-1.0.0-macosx_12_0_arm64-arm64.tar.gz
Traceback (most recent call last):
  File "/Users/nipunchamikara/Documents/Work/Wave/wave-example/venv/bin/wave", line 8, in <module>
    sys.exit(main())
  File "/Users/nipunchamikara/Documents/Work/Wave/wave-example/venv/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/nipunchamikara/Documents/Work/Wave/wave-example/venv/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/nipunchamikara/Documents/Work/Wave/wave-example/venv/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/nipunchamikara/Documents/Work/Wave/wave-example/venv/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/nipunchamikara/Documents/Work/Wave/wave-example/venv/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/nipunchamikara/Documents/Work/Wave/wave-example/venv/lib/python3.9/site-packages/h2o_wave/cli.py", line 211, in fetch
    request.urlretrieve(tar_url, tar_file)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

#### Expected behavior

The following expected output can be obtained when including `--platform=darwin`
```bash
Fetching examples and related files. Please wait...
Downloading https://github.com/h2oai/wave/releases/download/v1.0.0/wave-1.0.0-darwin-arm64.tar.gz
Extracting...

All additional files downloaded and extracted successfully!
Examples and tour............. /Users/nipunchamikara/Documents/Work/Wave/wave-example/wave/examples
Demos and layout samples...... /Users/nipunchamikara/Documents/Work/Wave/wave-example/wave/demo
Automated test harness........ /Users/nipunchamikara/Documents/Work/Wave/wave-example/wave/test
Wave daemon for deployments... /Users/nipunchamikara/Documents/Work/Wave/wave-example/wave
```

#### Steps To Reproduce

1. Initialize project with `h2o_wave` module installed
2. Run `wave fetch` in the terminal
3. Expect an error

**Comment by mturoci** [comment] 2023-11-08 09:49
Duplicate of #2177

**Closed by mturoci** 2023-11-08 09:49 UTC
Labels: bug
