### ISSUE TITLE
Component Enhancement: inline justify

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave#968] opened 2021-08-18 22:42 UTC
**MLOps project card:**
![image](https://user-images.githubusercontent.com/4793561/129981172-d7531ee1-d7ec-4859-b5aa-240781e9c99b.png)
![image](https://user-images.githubusercontent.com/4793561/129981207-aca4523f-4af9-4a8a-82a0-48e585e94808.png)

```python
page["project_2"] = ui.form_card(
    box="projects",
    items=[
        ui.text_xl("Project Name 2"),
        ui.inline(
            items=[
                ui.text("Owner: michelle@h2o.ai"),
                ui.text("Wed Aug 18 15:09:35 PDT 2021")
            ],
            justify="justify"  # functionality missing - we want these items to be at the start and end of the width
        ),
...
)
```

Today the only justify options for `ui.inline` are `start` and `end`. We would like to include a `justify` option which would be the equivalent to how text is shown in a newspaper - have items and the start and end, and equally spread in the middle as needed. 

https://xd.adobe.com/view/eebb600c-026b-4ca1-bb6b-0a439235452b-bbe8/specs/

**Comment by mturoci** [comment] 2021-08-19 07:16
Duplicate of #534

**Closed by mturoci** 2021-08-19 07:16 UTC
Labels: feature

**Comment by mturoci** [comment] 2021-08-19 07:25
@mtanco the feature you are describing is not achievable via `justify`. You need to control the width (Experiment count, 21, Deployed Model Version, 32 - all have to have the same width) which is introduced in #795.

The `inline` prop introduced in #534 will allow correct positioning of owner - date pair in your example.
