### ISSUE TITLE
There is no information about the Expando instance in the h2o wave app

### ISSUE THREAD

**Issue by sergiomora03** [h2oai/wave#468] opened 2021-01-04 15:01 UTC
#### Is your feature request related to a problem? Please describe

I tried to read more information about Expando instance: [`q.args`](https://h2oai.github.io/wave/docs/arguments/api/core#Expando) but had this error:

> *Page Not Found*
> We could not find what you were looking for.
> 
> Please contact the owner of the site that linked you to the original URL and let them know their link is broken.
> 

#### Describe the solution you'd like

Putting information about Expando instance.

#### Describe alternatives you've considered

Maybe there is a broken link.

**Comment by mturoci** [comment] 2021-01-04 15:13
Hi @sergiomora03, thanks for filling the issue. Could you please provide a gif / more detailed steps for reproduction? It seems like [this expando link](https://h2oai.github.io/wave/docs/api/core#Expando) is working. (After clicking _Expando_ here: 
![image](https://user-images.githubusercontent.com/64769322/103549468-b948e800-4ea7-11eb-8ff5-6441e50180c6.png))

**Comment by sergiomora03** [comment] 2021-01-04 16:11
Please check links again:

- You links me: https://h2oai.github.io/wave/docs/api/core/#Expando whom is working. 
- I gave you: https://h2oai.github.io/wave/docs/arguments/api/core#Expando wich is different link.

There is missing backslash in: https://h2oai.github.io/wave/docs/arguments/

Therefore, I create pull request #469. Please merge it to fix this.

**Comment by lo5** [comment] 2021-03-26 02:45
Duplicate of #445

**Closed by lo5** 2021-03-26 02:45 UTC
Labels: docs
