### ISSUE TITLE
Slider doesn't render inside ui.inline

### ISSUE THREAD

**Issue by vopani** [h2oai/wave#802] opened 2021-05-08 17:47 UTC
#### Wave SDK Version, OS
v0.15.0 in Chrome on Mac

#### Actual behaviour
Slider component doesn't render when used within `ui.inline`

#### Expected behaviour
Should render in same way as outside `ui.inline`

#### Steps To Reproduce
```python
from h2o_wave import main, Q, app, ui

@app('/demo')
async def serve(q: Q):
    q.page['test'] = ui.form_card(
        box='1 1 2 2',
        items=[
            ui.inline(
                items=[
                    ui.text('Select value:'),
                    ui.slider(name='slider', label='Slider', min=0, max=20, value=10)
                ]
            )
        ]
    )

    await q.page.save()
```

<img width="278" alt="Screenshot 2021-05-08 at 11 15 57 PM" src="https://user-images.githubusercontent.com/8954217/117548586-5df45580-b053-11eb-9afc-e134ced4ee69.png">

**Comment by mturoci** [comment] 2021-05-10 06:27
Duplicate of #582.

**Closed by mturoci** 2021-05-10 06:27 UTC
Labels: bug
